### ISSUE TITLE
Simplified Runtime Checker a la Erlang

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta-prototype#8]
# This Issue is WIP and will be rewritten based on the Purity Checker
@Deprecated{
Similar to the Erlang Compiler, we could resolve the totality of kotlin functions.
Kotlin already provides the User to detect if an Expression within a `When` or `If` clause is total. But, Arrow could extend this idea and inject type generators from the arrow-test engine or [propCheck](https://github.com/1Jajen1/propCheck) into the corresponding function. 
```
fun divZero(i:Int): Int = when {
   i < 0 -> i / 3
  else -> i / 0
} // throws `java.lang.ArithmeticException: / by zero`
```
1. We generate Code which simply injects an Int generator and tests the output type:
```
propCheck {
    forAll { i: Int ->
       divZero(i) is Int
    }
}
```
2. The compiler runs the Test in the same compilation step (Or the one where we're able to do this):

3. If the function throughs Exceptions, we delegate the output from arrow-test/ propCheck to the user or we customize the output - ideally with IntelliJ support.

I did not have time to investigate thoroughly in which Step we should generate the Tests as Synthetic Code and run them, but I'd like to hear your Feedback. I am reading some papers on Functional Testing and maybe there are more universal properties we can introduce alongside this example. Maybe we could also consult/ integrate [Jannis](https://github.com/1Jajen1). 
}

**Comment by raulraja** [comment]
Discussed offline with @i-walker that we can achieve this same functionality with #6
